relay:
  - http://172.80.80.47/deploy
repositories:
    zarkiel/SESSION:
        path: "/var/www/html/SESSION"
        clone_url: "https://titikaka.unap.edu.pe/zarkiel/SESSION.git"
        branch: "master"
    zarkiel/MODULES:
        path: "/var/www/html/MODULES"
        clone_url: "https://titikaka.unap.edu.pe/zarkiel/MODULES.git"
        branch: "master"
    zarkiel/USERS:
        path: "/var/www/html/USERS"
        clone_url: "https://titikaka.unap.edu.pe/zarkiel/USERS.git"
        branch: "master"
    zarkiel/ROLES:
        path: "/var/www/html/ROLES"
        clone_url: "https://titikaka.unap.edu.pe/zarkiel/ROLES.git"
        branch: "master"
    zarkiel/EMAIL:
        path: "/var/www/html/EMAIL"
        clone_url: "https://titikaka.unap.edu.pe/zarkiel/EMAIL.git"
        branch: "master"